name: Test and Deploy

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run bundle install
        run: |
          bundle config --local path vender/bundle
          bundle config --local without production
          bundle install

      - run: RAILS_ENV=test bundle exec rails assets:precompile

      - run: bundle exec rails test
